In [5]:
import pandas as pd
import sqlite3
import numpy as np

In [6]:
conn = sqlite3.connect('people_detection.db')

In [7]:
pd.read_sql_query("SELECT COUNT(*) from boxes;", conn)

    COUNT(*)
0  115343867

In [8]:
pd.read_sql_query("SELECT COUNT(DISTINCT seq_path) FROM boxes;", conn)

   COUNT(DISTINCT seq_path)
0                      9634

In [9]:
df_seq = pd.read_sql_query("SELECT DISTINCT seq_name FROM boxes;", conn)
df_seq.shape

(9634, 1)

In [10]:
df_seq["seq_name"].unique().shape

(9634,)

In [12]:
df = pd.read_csv("tmp/data_deduplicated.csv")
df.shape

(21585, 5)

In [13]:
diff = list(set(df["seq_name"].values).difference(df_seq["seq_name"].values))

In [14]:
len(diff)

11951

In [15]:
diff[0]

't23_cross_27_11_57_49_2015.avi.seq'

In [16]:
df.shape

(21585, 5)

In [17]:
df.dropna().shape

(21585, 5)

In [18]:
df[df["seq_name"] == diff[0]]["seq_path"].values

array(['/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling_POV/Occupancy/OCS_Short_Scenario_Crossing_H253cm_10fps_PIRch01/t23_cross_27_11_57_49_2015.avi.seq'],
      dtype=object)

In [20]:
df.head()

,seq_path,is_algo_test,vlc,video_path,seq_name
0,/mnt/pg-fs02/Public/DB_Team/PG1/Variance/Point...,False,False,/mnt/pg-fs02/Public/DB_Team/PG1/Variance/Point...,SP_SNY110FOV_35Deg_101_1_Stnd_ZivCo_Thu_Aug_14...
1,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,False,False,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,CROSS_type_C_PN_lens_110x93_02_11_47_39_2015.a...
2,/mnt/pg-fs02/Public/DB_Team/PG1/Benchmarks/0_m...,False,False,/mnt/pg-fs02/Public/DB_Team/PG1/Benchmarks/0_m...,PG1_H300_HD_PG_stitch170718_06a_1499764142.avi...
3,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,False,False,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,PG1_DL_H270_Neg_Chair_Wline_NY_1499848884.avi.seq
4,/mnt/pg-fs01/Current/DB_QA/Home_Appliance/Ceil...,False,False,/mnt/pg-fs01/Current/DB_QA/Home_Appliance/Ceil...,QA_H253_Cross_Short_Intersection_NoSw_Jul_08_0...

In [21]:
import pickle

with open("tmp/import_statuses.pickle", "rb") as f:
    res = pickle.load(f)

In [22]:
len(res)

32

In [23]:
import glob
import subprocess
from tqdm import tqdm
import pickle


files = glob.glob("tmp/results/*.txt")

In [24]:
names = []
for file in tqdm(files):
    df = pd.read_csv(file, header=None, names=[
        "seq_name",
        "seq_path",
        "avi_path",
        "frame_h",
        "frame_w",
        "camera_type",
        "altitude",
        "frame_n",
        "user_id",
        "left",
        "top",
        "width",
        "height",
        "pos_x",
        "pos_y"
    ])
    names.append(df["seq_name"].unique())

names = np.concatenate(names)

  0%|          | 0/32 [00:00<?, ?it/s]

 22%|██▏       | 7/32 [01:13<04:20, 10.41s/it]/tmp/ipykernel_455366/1491655408.py:3: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 28%|██▊       | 9/32 [01:34<04:02, 10.53s/it]/tmp/ipykernel_455366/1491655408.py:3: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
100%|██████████| 32/32 [05:29<00:00, 10.30s/it]

In [25]:
np.unique(names).shape

(9634,)

In [26]:
df[df["seq_name"] == diff[0]]

Empty DataFrame
Columns: [seq_name, seq_path, avi_path, frame_h, frame_w, camera_type, altitude, frame_n, user_id, left, top, width, height, pos_x, pos_y]
Index: []