In [23]:
import pandas as pd
import sqlite3
import numpy as np

In [24]:
conn = sqlite3.connect('object_detection.db')

In [3]:
pd.read_sql_query("SELECT COUNT(*) from boxes;", conn)

   COUNT(*)
0  82016548

In [25]:
pd.read_sql_query("SELECT COUNT(DISTINCT seq_path) FROM boxes;", conn)

   COUNT(DISTINCT seq_path)
0                      6288

In [5]:
df_seq = pd.read_sql_query("SELECT DISTINCT seq_name FROM boxes;", conn)
df_seq.shape

(6288, 1)

In [8]:
df_seq["seq_name"].unique().shape

(6288,)

In [47]:
df = pd.read_csv("data_deduplicated.csv")
df.shape

(12842, 7)

In [48]:
diff = list(set(df["seq_name"].values).difference(df_seq["seq_name"].values))

In [49]:
len(diff)

6554

In [50]:
diff[0]

't22_Shtr_Apr_21_11_46_09_2015.avi.seq'

In [51]:
df.shape

(12842, 7)

In [17]:
df.dropna().shape

(6012, 7)

In [54]:
df[df["seq_name"] == diff[0]]["seq_path"].values

array(['/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling_POV/Occupancy/OCS_Noise_Scenario_H253cm_10fps_PIRch01/t22_Shtr_Apr_21_11_46_09_2015.avi.seq'],
      dtype=object)

In [22]:
df[~df["altitude"].notna()]

,seq_path,is_algo_test,altitude,device_type,vlc,video_path,seq_name
0,/mnt/pg-fs01/Current/Benchmarks/ABC/aaa.avi.seq,False,NaN,NaN,False,/mnt/pg-fs01/current/DB/Home_Appliance/Ceiling...,aaa.avi.seq
1,/mnt/pg-fs01/Current/Benchmarks/ABC/bbb.avi.seq,False,NaN,NaN,False,/mnt/pg-fs01/current/DB/Home_Appliance/Ceiling...,bbb.avi.seq
2,/mnt/pg-fs01/Current/Benchmarks/ABC/ccc.avi.seq,False,NaN,NaN,False,/mnt/pg-fs01/current/DB/Home_Appliance/Ceiling...,ccc.avi.seq
1798,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,False,NaN,NaN,False,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,01_Mon_Dec_22_09_53_18_2014.avi.seq
1799,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,False,NaN,NaN,False,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,01_Sun_Dec_21_16_53_16_2014.avi.seq
...,...,...,...,...,...,...,...
12829,/mnt/pg-fs02/Users/Yevgen/VLC test video/video...,False,NaN,NaN,True,/mnt/pg-fs02/Users/Yevgen/VLC test video/video...,video_3.avi.seq
12830,/mnt/pg-fs02/Users/Yevgen/VLC test video/video...,False,NaN,NaN,True,/mnt/pg-fs02/Users/Yevgen/VLC test video/video...,video_4.avi.seq
12832,/mnt/pg-fs02/Users/forMoshe/record_1510495001....,False,NaN,NaN,False,/mnt/pg-fs02/Users/forMoshe/record_1510495001.avi,record_1510495001.avi.seq
12833,/mnt/pg-fs02/Users/forMoshe/record_1510495084....,False,NaN,NaN,False,/mnt/pg-fs02/Users/forMoshe/record_1510495084.avi,record_1510495084.avi.seq
12834,/mnt/pg-fs02/Users/forMoshe/record_1510495157....,False,NaN,NaN,False,/mnt/pg-fs02/Users/forMoshe/record_1510495157.avi,record_1510495157.avi.seq

In [26]:
import pickle

with open("import_statuses.pickle", "rb") as f:
    res = pickle.load(f)

In [27]:
len(res)

32

In [31]:
import glob
import subprocess
from tqdm import tqdm
import pickle


files = glob.glob("results/*.txt")

In [43]:
names = []
for file in tqdm(files):
    df = pd.read_csv(file, header=None, names=[
        "seq_name",
        "seq_path",
        "avi_path",
        "frame_h",
        "frame_w",
        "camera_type",
        "altitude",
        "frame_n",
        "user_id",
        "left",
        "top",
        "width",
        "height",
        "pos_x",
        "pos_y"
    ])
    names.append(df["seq_name"].unique())

names = np.concatenate(names)

  0%|          | 0/32 [00:00<?, ?it/s]

/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
  3%|▎         | 1/32 [00:05<02:55,  5.65s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
  6%|▋         | 2/32 [00:10<02:43,  5.45s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
  9%|▉         | 3/32 [00:16<02:44,  5.69s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 16%|█▌        | 5/32 [00:27<02:29,  5.54s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 19%|█▉        | 6/32 [00:34<02:29,  5.76s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 22%|██▏       | 7/32 [00:39<02:20,  5.62s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 25%|██▌       | 8/32 [00:45<02:17,  5.71s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 28%|██▊       | 9/32 [00:50<02:10,  5.66s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 31%|███▏      | 10/32 [00:56<02:08,  5.82s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 34%|███▍      | 11/32 [01:03<02:05,  6.00s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 38%|███▊      | 12/32 [01:09<02:02,  6.12s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 41%|████      | 13/32 [01:16<01:57,  6.16s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 44%|████▍     | 14/32 [01:22<01:51,  6.17s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 47%|████▋     | 15/32 [01:28<01:43,  6.09s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 50%|█████     | 16/32 [01:34<01:38,  6.18s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 53%|█████▎    | 17/32 [01:40<01:30,  6.04s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 56%|█████▋    | 18/32 [01:46<01:24,  6.03s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 59%|█████▉    | 19/32 [01:52<01:20,  6.17s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 62%|██████▎   | 20/32 [01:58<01:13,  6.12s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 66%|██████▌   | 21/32 [02:04<01:06,  6.05s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 69%|██████▉   | 22/32 [02:10<01:00,  6.06s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 72%|███████▏  | 23/32 [02:17<00:55,  6.21s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 75%|███████▌  | 24/32 [02:23<00:50,  6.25s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 81%|████████▏ | 26/32 [02:36<00:37,  6.28s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 84%|████████▍ | 27/32 [02:42<00:31,  6.39s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 88%|████████▊ | 28/32 [02:48<00:24,  6.11s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 91%|█████████ | 29/32 [02:55<00:18,  6.26s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 94%|█████████▍| 30/32 [03:00<00:12,  6.08s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
 97%|█████████▋| 31/32 [03:06<00:06,  6.01s/it]/tmp/ipykernel_646086/1491655408.py:3: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, header=None, names=[
100%|██████████| 32/32 [03:13<00:00,  6.03s/it]

In [44]:
np.unique(names).shape

(6288,)

In [46]:
df[df["seq_name"] == diff[0]]

Empty DataFrame
Columns: [seq_name, seq_path, avi_path, frame_h, frame_w, camera_type, altitude, frame_n, user_id, left, top, width, height, pos_x, pos_y]
Index: []