In [15]:
import os
import sys
import json
import shutil
import glob

import pandas as pd
import sqlite3
import cv2
import numpy as np
import tqdm
import time
import matplotlib.pyplot as plt
import yaml
from tqdm.contrib.concurrent import thread_map

sys.path.append("../../../PG_PyTraining")
from common.pg.cam_params import get_camparams
import splitter

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
with open("../video_similarity/splitting.json", "rt") as f:
    data_splitting = json.load(f)

df_video = pd.read_csv("../seq_files.csv")
df_video.dropna(inplace=True)
print(df_video.shape)
df_video.head()

(8440, 7)

,seq_name,seq_path,avi_path,frame_h,frame_w,camera_type,altitude
1,PG1_dev_H660_Walk_Q_BlackCarpet_NY_Q_150928576...,/mnt/pg-fs01/Current/Benchmarks/PG1_AlgoDev2_h...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG_Camera,660
2,PG1_DL_H300_Walking_NY_St1707_1500538480.avi.seq,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG1_Camera1,300
3,PG1_dev_H270_VLC_3mHall_Door_05Wall_1509468343...,/mnt/pg-fs01/Current/Benchmarks/PG1_AlgoDev_VL...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG_Camera,270
4,PG1_H300_MR_SquareSeat_NY_15stnd_1509274685.av...,/mnt/pg-fs01/Current/Benchmarks/PG1_AlgoDev_DL...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG_Camera,300
5,PG1_Q_H300_1L_Tilt_Batzra_S05_07_09_26_26_2016...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG1_Camera1,300

In [14]:
x = "/mnt/pg-fs02/Users/Maor/yuval/Barak's Temp/temp_barak/backup/PG1_DL_H250_Walking_lineShirt_02_11_05_45_2017.avi.seq"

conn_wrapper = splitter.SQLLiteWrapper(DB_PTH)
conn_wrapper.get_dets(x)

      frame_n  frame_h  frame_w  x_left  y_top  width  height  pos_x  pos_y
0           0      960     1280      76      0    118      72    151     39
1           0      960     1280     273      0    122      31    325      6
2           0      960     1280     478      0    123      55    556     25
3           0      960     1280     716      0    100      42    773     12
4           0      960     1280     982      0    122      84   1026     37
...       ...      ...      ...     ...    ...    ...     ...    ...    ...
9372     1565      960     1280     245    863    120      95    326    899
9373     1565      960     1280     437    860    122      98    503    899
9374     1565      960     1280     696    851     97     107    740    884
9375     1565      960     1280     924    832    109     123    954    887
9376     1565      960     1280    1097    838    156     120   1152    880

[9377 rows x 9 columns]

In [24]:
labels_folders = glob.glob(os.path.join(splitter.DATABASE_BASE_PTH, "baseline", "labels", "*"))
for label_folder in labels_folders:
    print(len(glob.glob(os.path.join(label_folder, "*.txt"))))

76510