In [5]:
import os

import pandas as pd

In [22]:
BASE_PATH = "../../../../data/ObjectDetectionV3_1"

df = pd.read_csv(os.path.join(BASE_PATH, "images.csv"))
print("'images' table shape", df.shape)

df_annotations = pd.read_csv(os.path.join(BASE_PATH, "annotation_merged_furniture.csv"))
df_base = pd.read_csv(os.path.join(BASE_PATH, "annotation.csv"))

'images' table shape (710, 9)

In [7]:
df

,id,name,width,height,batch,folder,task_id,job_id,job_url
0,bdd640fb-0667-4ad1-9c80-317fa3b1799d,Cam2_H255_discaunt_29012024_2024-02-06-11h11m0...,640,480,batchai1-11.7,1,653525,832182,https://app.cvat.ai/tasks/653525/jobs/832182
1,b74d0fb1-32e7-4629-8fad-c1a606cb0fb3,Cam2_H255_discaunt_29012024_2024-02-06-11h11m1...,640,480,batchai1-11.7,1,653525,832182,https://app.cvat.ai/tasks/653525/jobs/832182
2,1a2a73ed-562b-4f79-8374-59eef50bea63,Cam2_H255_discaunt_29012024_2024-02-06-11h11m1...,640,480,batchai1-11.7,1,653525,832182,https://app.cvat.ai/tasks/653525/jobs/832182
3,e2acf72f-9e57-4f7a-a0ee-89aed453dd32,Cam2_H255_discaunt_29012024_2024-02-06-11h11m1...,640,480,batchai1-11.7,1,653525,832182,https://app.cvat.ai/tasks/653525/jobs/832182
4,29a3b2e9-5d65-4441-9588-42dea2bc372f,Cam2_H255_discaunt_29012024_2024-02-06-11h11m2...,640,480,batchai1-11.7,1,653525,832182,https://app.cvat.ai/tasks/653525/jobs/832182
...,...,...,...,...,...,...,...,...,...
705,3b3f3679-8b1c-49cb-af9d-3fe4119581d3,Cam3_H243_discount_19.png,640,480,batchai1-11.7,9,654812,833377,https://app.cvat.ai/tasks/654812/jobs/833377
706,27a893df-e420-4f84-85c2-3771297fa0b9,Cam3_H245_discount_1.png,640,480,batchai1-11.7,9,654812,833377,https://app.cvat.ai/tasks/654812/jobs/833377
707,10ba4973-d990-4381-87d7-35732374585c,Cam3_H245_discount_2.png,640,480,batchai1-11.7,9,654812,833377,https://app.cvat.ai/tasks/654812/jobs/833377
708,a6874c45-ef5e-4d02-9f79-a7a56645b7de,Cam3_H245_discount_3.png,640,480,batchai1-11.7,9,654812,833377,https://app.cvat.ai/tasks/654812/jobs/833377
709,dd139c4c-9daf-4ca0-9b20-2c86e9261454,Cam3_H245_discount_4.png,640,480,batchai1-11.7,9,654812,833377,https://app.cvat.ai/tasks/654812/jobs/833377

In [33]:
tmp = df[df["id"].str.contains("9d4c")]
tmp

,id,name,width,height,batch,folder,task_id,job_id,job_url
622,04b2047f-44aa-4939-9d4c-3a4f63203749,Cam3_H250_spacesks_MR1_12024-02-18-23h50m02s35...,640,480,batchai1-11.7,5,656883,835523,https://app.cvat.ai/tasks/656883/jobs/835523

In [12]:
print(tmp['name'].values)

['PG1_DL_H300_office_Beige_uTable_21_11_00_46_2016.avi_snapshot_00.30.528.bmp']

In [13]:
print(tmp['job_url'].values)

['https://app.cvat.ai/tasks/667992/jobs/847677']

In [15]:
name = "PG1_DL_H300_office_Beige_uTable_21_10_02_38_2016.avi_snapshot_00.01.268.bmp"

In [17]:
df[df["name"] == name]

,id,name,width,height,batch,folder,task_id,job_id,job_url
87,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,PG1_DL_H300_office_Beige_uTable_21_10_02_38_20...,1280,960,batchai1-11.7,15,667992,847677,https://app.cvat.ai/tasks/667992/jobs/847677

In [20]:
df_annotations[(df_annotations["img_id"] == "f83b1806-ee4c-4b18-96a2-d49d9e5f8273") & (df_annotations["label"] == "table")]

,label,not_ground,truncated,occluded,occupied_by_person,occupied,ID,xtl,ytl,xbr,ybr,x,y,img_id,id,corners
1819,table,False,False,True,False,False,20.0,671.10,512.99,961.07,775.23,824.70,671.80,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,05776108-3166-4c94-bbb2-4366704fe1a8,NaN
1820,table,False,False,True,False,False,21.0,454.04,630.15,724.56,877.07,616.78,780.77,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,b972393a-5bb0-4d76-a0b5-7717b072afc8,NaN
1821,table,False,False,False,False,False,22.0,350.74,60.98,940.07,521.76,660.15,271.18,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,8f1c3fa0-7000-4009-b4e5-70ba7c3cc2bc,"[360.24, 330.74, 453.29, 508.51, 928.35, 244.5..."
1822,table,False,False,True,False,False,11.0,337.39,820.59,427.93,935.41,377.11,888.35,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,730ad7de-27af-4ff9-87f8-9f6211a1e557,NaN

In [24]:
df_base[(df_base["img_id"] == "f83b1806-ee4c-4b18-96a2-d49d9e5f8273") & (df_base["label"] == "desk")]

,label,not_ground,truncated,occluded,occupied_by_person,occupied,ID,xtl,ytl,xbr,ybr,x,y,img_id,id,corners
2148,desk,False,False,True,False,False,20.0,678.59,531.71,961.01,775.67,817.37,683.19,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,e44cbd41-ce36-492a-98e9-d0aac1b6edd4,"[689.2, 687.38, 727.14, 768.37, 954.1, 626.5, ..."
2151,desk,False,False,True,False,False,21.0,458.49,677.54,724.47,882.69,606.90,789.80,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,0a1bebd3-e60e-4813-802d-a0fa227dcecc,"[468.2, 796.09, 525.11, 870.51, 719.9, 770.3, ..."
2152,desk,False,False,False,False,False,22.0,350.74,60.98,940.07,521.76,660.15,271.18,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,8f1c3fa0-7000-4009-b4e5-70ba7c3cc2bc,"[360.24, 330.74, 453.29, 508.51, 928.35, 244.5..."

In [27]:
df_a = df_base[(df_base["img_id"] == "f83b1806-ee4c-4b18-96a2-d49d9e5f8273") & (df_base["label"] == "desk_FULL")]
df_b = df_base[(df_base["img_id"] == "f83b1806-ee4c-4b18-96a2-d49d9e5f8273") & (df_base["label"] == "desk")]

In [28]:
df_a

,label,not_ground,truncated,occluded,occupied_by_person,occupied,ID,xtl,ytl,xbr,ybr,x,y,img_id,id,corners
2149,desk_FULL,False,False,True,False,False,20.0,671.10,512.99,961.07,775.23,824.70,671.80,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,05776108-3166-4c94-bbb2-4366704fe1a8,NaN
2150,desk_FULL,False,False,True,False,False,21.0,454.04,630.15,724.56,877.07,616.78,780.77,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,b972393a-5bb0-4d76-a0b5-7717b072afc8,NaN

In [29]:
df_b

,label,not_ground,truncated,occluded,occupied_by_person,occupied,ID,xtl,ytl,xbr,ybr,x,y,img_id,id,corners
2148,desk,False,False,True,False,False,20.0,678.59,531.71,961.01,775.67,817.37,683.19,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,e44cbd41-ce36-492a-98e9-d0aac1b6edd4,"[689.2, 687.38, 727.14, 768.37, 954.1, 626.5, ..."
2151,desk,False,False,True,False,False,21.0,458.49,677.54,724.47,882.69,606.90,789.80,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,0a1bebd3-e60e-4813-802d-a0fa227dcecc,"[468.2, 796.09, 525.11, 870.51, 719.9, 770.3, ..."
2152,desk,False,False,False,False,False,22.0,350.74,60.98,940.07,521.76,660.15,271.18,f83b1806-ee4c-4b18-96a2-d49d9e5f8273,8f1c3fa0-7000-4009-b4e5-70ba7c3cc2bc,"[360.24, 330.74, 453.29, 508.51, 928.35, 244.5..."

In [30]:
df_base[(df_base["img_id"] == '9c1c3517-85d2-40a6-8629-5b5d707df251') & (df_base["label"] == "desk")]

,label,not_ground,truncated,occluded,occupied_by_person,occupied,ID,xtl,ytl,xbr,ybr,x,y,img_id,id,corners
595,desk,False,False,False,False,False,12.0,268.16,327.45,397.00,396.34,333.77,361.33,9c1c3517-85d2-40a6-8629-5b5d707df251,eafde7d9-5f73-4a3e-9d28-6aa428a39779,"[389.92, 340.8, 382.8, 386.2, 277.77, 382.83, ..."
596,desk,False,False,False,False,False,17.0,487.12,45.95,582.55,266.21,NaN,NaN,9c1c3517-85d2-40a6-8629-5b5d707df251,c6435300-68a5-4c68-a32d-bb5e486bb6bf,NaN
599,desk,False,False,True,False,False,10.0,230.23,15.79,377.17,198.75,305.54,107.21,9c1c3517-85d2-40a6-8629-5b5d707df251,8ed6ad5e-1831-4aa3-9466-9d1910df9974,"[364.17, 28.94, 257.06, 29.39, 241.63, 180.08,..."
602,desk,False,False,False,False,False,13.0,557.93,316.43,625.52,373.62,598.29,344.75,9c1c3517-85d2-40a6-8629-5b5d707df251,267eddce-df8f-4197-9a4a-99b2e806133c,"[618.36, 325.51, 609.53, 355.14, 566.35, 367.1..."
623,desk,False,False,False,False,False,11.0,NaN,NaN,NaN,NaN,542.71,158.04,9c1c3517-85d2-40a6-8629-5b5d707df251,9feefdff-c566-4a81-b15e-54f6d4d30795,"[566.7, 81.92, 498.61, 57.34, 499.24, 252.76, ..."

In [31]:
df[df["id"] == '9c1c3517-85d2-40a6-8629-5b5d707df251']

,id,name,width,height,batch,folder,task_id,job_id,job_url
40,9c1c3517-85d2-40a6-8629-5b5d707df251,Cam3_H270_spacesks_os2_12024-03-03-20h00m44s54...,640,480,batchai1-11.7,13,658840,837574,https://app.cvat.ai/tasks/658840/jobs/837574

In [32]:
df[df["id"] == '9c1c3517-85d2-40a6-8629-5b5d707df251'].values

array([['9c1c3517-85d2-40a6-8629-5b5d707df251',
        'Cam3_H270_spacesks_os2_12024-03-03-20h00m44s549.png', 640, 480,
        'batchai1-11.7', 13, 658840, 837574,
        'https://app.cvat.ai/tasks/658840/jobs/837574']], dtype=object)