In [14]:
import pandas as pd
import os
import numpy as np

In [2]:
df = pd.read_csv("../seq_files.csv")
df.head()

,seq_name,seq_path,avi_path,frame_h,frame_w,camera_type,altitude
0,Noise_1_enter_exit_NoSw_28_16_15_11_2015.avi.seq,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,720.0,1280.0,NaN,253
1,PG1_dev_H660_Walk_Q_BlackCarpet_NY_Q_150928576...,/mnt/pg-fs01/Current/Benchmarks/PG1_AlgoDev2_h...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG_Camera,660
2,PG1_DL_H300_Walking_NY_St1707_1500538480.avi.seq,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG1_Camera1,300
3,PG1_dev_H270_VLC_3mHall_Door_05Wall_1509468343...,/mnt/pg-fs01/Current/Benchmarks/PG1_AlgoDev_VL...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG_Camera,270
4,PG1_H300_MR_SquareSeat_NY_15stnd_1509274685.av...,/mnt/pg-fs01/Current/Benchmarks/PG1_AlgoDev_DL...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG_Camera,300

In [4]:
df[df["seq_name"] == "PG1_DL_H300_Office_desk_NY_17_12_37_23_2017.avi.seq"].values

array([['PG1_DL_H300_Office_desk_NY_17_12_37_23_2017.avi.seq',
        '/mnt/pg-fs02/Public/DB_Team/PG1/0_Orange_IT/0_Paid_UNTIL_2017_06_20_1500$_AND_3X850$_move2db/2017_05_17_H300_DL_NY_Tag_145057_WithPos_move2pos06/done_db_pose/PG1_DL_H300_Office_desk_NY_17_12_37_23_2017.avi.seq',
        '/mnt/pg-fs02/Public/DB_Team/PG1/0_Orange_IT/0_Paid_UNTIL_2017_06_20_1500$_AND_3X850$_move2db/2017_05_17_H300_DL_NY_Tag_145057_WithPos_move2pos06/done_db_pose/PG1_DL_H300_Office_desk_NY_17_12_37_23_2017.avi',
        960.0, 1280.0, 'SunPlus_PG1_Camera1', '300']], dtype=object)

In [28]:
df[df["seq_name"] == "PG1_H655_dev_Office_HD_NY_180320-180758.avi.seq"].values

array([['PG1_H655_dev_Office_HD_NY_180320-180758.avi.seq',
        '/mnt/pg-fs02/Public/DB_Team/PG1/Benchmarks/0_To_Mark/PG1_2018_03_29_H655_Office_HD_NY/done/PG1_H655_dev_Office_HD_NY_180320-180758.avi.seq',
        '/mnt/pg-fs02/Public/DB_Team/PG1/Benchmarks/0_To_Mark/PG1_2018_03_29_H655_Office_HD_NY/done/PG1_H655_dev_Office_HD_NY_180320-180758.avi',
        960.0, 1280.0, 'SunPlus_PG_Camera', '655']], dtype=object)

In [6]:
os.path.exists('/mnt/pg-fs02/Public/DB_Team/PG1/0_Orange_IT/0_Paid_UNTIL_2017_06_20_1500$_AND_3X850$_move2db/2017_05_17_H300_DL_NY_Tag_145057_WithPos_move2pos06/done_db_pose/PG1_DL_H300_Office_desk_NY_17_12_37_23_2017.avi.seq')

True

In [7]:
os.path.exists("/mnt/pg-fs02/Public/DB_Team/PG1/0_Orange_IT/0_Paid_UNTIL_2017_06_20_1500$_AND_3X850$_move2db/2017_05_17_H300_DL_NY_Tag_145057_WithPos_move2pos06/done_db_pose/PG1_DL_H300_Office_desk_NY_17_12_37_23_2017.avi")

True

In [8]:
df.shape

(9634, 7)

In [10]:
df["seq_name"].unique().shape

(9634,)

In [11]:
df[df["avi_path"].isin([
    "/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling_POV/PG1_DL/PG1_DL_training_POS08_Desk/PG1_DL_H300_Office_Desk_NY_17_12_37_23_2017.avi",
    "/mnt/pg-fs02/Public/DB_Team/PG1/0_Orange_IT/0_Paid_UNTIL_2017_06_20_1500$_AND_3X850$_move2db/2017_05_17_H300_DL_NY_Tag_145057_WithPos_move2pos06/done_db_pose/PG1_DL_H300_Office_desk_NY_17_12_37_23_2017.avi"
])]

,seq_name,seq_path,avi_path,frame_h,frame_w,camera_type,altitude
7118,PG1_DL_H300_Office_desk_NY_17_12_37_23_2017.av...,/mnt/pg-fs02/Public/DB_Team/PG1/0_Orange_IT/0_...,/mnt/pg-fs02/Public/DB_Team/PG1/0_Orange_IT/0_...,960.0,1280.0,SunPlus_PG1_Camera1,300
9003,PG1_DL_H300_Office_Desk_NY_17_12_37_23_2017.av...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,/mnt/pg-fs01/Current/DB/Home_Appliance/Ceiling...,960.0,1280.0,SunPlus_PG1_Camera1,300

In [13]:
df["seq_name"].str.lower().unique().shape

(9600,)

In [24]:
names, counts = np.unique(df["seq_name"].str.lower().values, return_counts=True)

In [16]:
df["seq_name"].str.lower().shape

(9634,)

In [17]:
np.unique(df["seq_name"].str.lower()).shape

(9600,)

In [26]:
names[counts > 1]

array(['pg1_dl_h260_office_desk_17_13_01_10_2017.avi.seq',
       'pg1_dl_h260_office_desk_17_13_04_38_2017.avi.seq',
       'pg1_dl_h260_office_desk_17_13_13_25_2017.avi.seq',
       'pg1_dl_h260_office_desk_17_13_17_29_2017.avi.seq',
       'pg1_dl_h260_office_desk_17_13_24_09_2017.avi.seq',
       'pg1_dl_h260_office_desk_17_13_27_11_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_14_55_01_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_15_05_18_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_15_08_20_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_15_14_08_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_15_17_14_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_15_21_05_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_16_03_46_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_16_06_55_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_16_20_32_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_16_23_40_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_16_26_58_2017.avi.seq',
       'pg1_dl_h300_office_desk_17_16_37_24_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_11_14_42_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_11_23_45_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_11_34_47_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_11_40_56_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_11_45_08_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_11_48_18_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_11_52_38_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_11_56_15_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_12_00_42_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_12_04_20_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_12_26_45_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_12_30_01_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_12_34_10_2017.avi.seq',
       'pg1_dl_h300_office_desk_ny_17_12_37_23_2017.avi.seq',
       'pg1_dl_h300_office_desk_sl_oc_1495194686.avi.seq',
       'pg1_dl_h300_office_desk_sl_oc_1495195172.avi.seq'], dtype=object)

In [27]:
counts[counts > 1]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])